// <auto-generated />
namespace MVCGrid.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Firstl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Firstl));
        
        string IMigrationMetadata.Id
        {
            get { return "202007071420044_Firstl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
