// <auto-generated />
namespace MVCGrid.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Firstlm : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Firstlm));
        
        string IMigrationMetadata.Id
        {
            get { return "202007071421499_Firstlm"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
